### ISSUE TITLE
Following build errors.

### ISSUE THREAD

**Issue by brad2192** [GameProgressive/RetroSpyServer#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	2 unresolved externals	DatabaseServer	C:\RetroSpyServer-master\Debug\DatabaseServer.exe	1	
Error (active)	E0165	too few arguments in function call	ConnectionManagerServer	c:\RetroSpyServer-master\ConnectionManagerServer\GPCMServer.c	7	
Error (active)	E0065	expected a ';'	ConnectionManagerServer	c:\RetroSpyServer-master\ConnectionManagerServer\GPCMServer.c	29	
Error	C2198	'serverWriteString': too few arguments for call	ConnectionManagerServer	c:\retrospyserver-master\connectionmanagerserver\gpcmserver.c	7	
Error	C2143	syntax error: missing ';' before '{'	ConnectionManagerServer	c:\retrospyserver-master\connectionmanagerserver\gpcmserver.c	29	
Error	C1075	the left brace '{' was unmatched at the end of the file	ConnectionManagerServer	c:\retrospyserver-master\connectionmanagerserver\gpcmserver.c	11	
Error	LNK2019	unresolved external symbol _SAFE_SQLITE_FREE referenced in function _database_exec	DatabaseServer	C:\RetroSpyServer-master\DatabaseServer\DBManager.obj	1	
Error	LNK2001	unresolved external symbol _sqlite3_version	DatabaseServer	C:\RetroSpyServer-master\DatabaseServer\sqlite3.obj	1	

Also, is the compatible for Playstation Gamespy Emulation?

**Comment by arves100** [comment]
Hello, thanks for you issue.
The current build dosen't work because it's missing some features on ConnectionManager and DatabaseServer. You could test the Authentication Server with an old commit like "0872d19a1bfad9b4e84a0d76075724a0a23cd385"
Also, i don't have a PS2/PS3 system to test the server, you could tell me if it works.
